# Generated by Django 4.2.6 on 2023-10-21 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_path", models.CharField(max_length=50)),
                ("request_method", models.CharField(max_length=50)),
                ("execution_time", models.FloatField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="studentsgroup",
            name="teacher",
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="studentsgroup",
            name="student",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="school.student",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="score",
            field=models.IntegerField(default="1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="photo",
            field=models.ImageField(default="photo", upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.teacher"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_year",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="studentsgroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.group"
            ),
        ),
        migrations.RemoveField(
            model_name="subject",
            name="teacher",
        ),
        migrations.DeleteModel(
            name="TeacherSubject",
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="school.teacher",
            ),
            preserve_default=False,
        ),
    ]
