# Generated by Django 4.2.5 on 2023-10-11 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="teacher",
        ),
    ]
