# Generated by Django 4.2.6 on 2023-10-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_remove_student_teacher_remove_subject_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="score",
            field=models.IntegerField(default="1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.PROTECT,
                to="school.teacher",
            ),
            preserve_default=False,
        ),
    ]
