# Generated by Django 4.2.6 on 2023-10-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0006_alter_student_admission_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentsgroup",
            name="group",
        ),
        migrations.AddField(
            model_name="studentsgroup",
            name="student",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="school.student",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="TeacherSubject",
        ),
    ]
