# Generated by Django 4.2.6 on 2023-10-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_studentsgroup_group_studentsgroup_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsgroup',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentsgroup',
            name='group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='school.group'),
            preserve_default=False,
        ),
    ]
