# Generated by Django 4.2.6 on 2023-10-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0008_remove_studentsgroup_teacher_studentsgroup_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_path", models.CharField(max_length=50)),
                ("request_method", models.CharField(max_length=50)),
                ("execution_time", models.FloatField(max_length=20)),
            ],
        ),
    ]
