# Generated by Django 4.2.6 on 2023-10-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0009_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
