# Generated by Django 4.2.6 on 2023-10-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0010_student_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_year",
            field=models.IntegerField(unique_for_year="2000-2010"),
        ),
    ]
