# Generated by Django 4.2.6 on 2023-10-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0011_alter_student_admission_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_year",
            field=models.CharField(max_length=4),
        ),
    ]
